### ISSUE TITLE
SQLInsertBuilder and SQLUpdateBuilder do not expose the ignore flag

### ISSUE THREAD

**Issue by 0xTim** [vapor/sql-kit#22] opened 2018-07-08 21:05 UTC
While it is possible to issue an `INSERT IGNORE` (or other database equivalent) query at the Fluent level using `Model.create(orIgnore:on:)`, it is not possible to issue the same query at the `SQL` level using `SQLInsertBuilder` - one must build the appropriate `SQLInsert` object manually or use a raw query. Once Fluent supports `UPDATE IGNORE`, a similar issue will exist for `SQLUpdateBuilder` as well. The best API for this is probably a simple `public func ignore(_ flag: Bool = true) -> Self` function on both builders.

**Comment by tanner0101** [comment] 2020-04-22 15:45
Duplicate of https://github.com/vapor/sql-kit/issues/31

**Closed by tanner0101** 2020-04-22 15:45 UTC
Labels: enhancement
